import type { Metadata } from "next";
import { Inter, Lato, Josefin_Sans  } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/TopBar";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });
const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'], 
});


export const metadata: Metadata = {
  title: "Hakathon",
  description: "Generated by create next app",
};
const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  weight: ['400', '700'], 
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} ${josefinSans.className} {${inter.className}`}>
        <TopBar />
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
